#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PicassoSample.Resource", IsApplication=true)]

namespace PicassoSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int list_divider = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int overlay_selector_pressed = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int window_background = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int faux_action_bar_size = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int list_detail_image_size = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int notification_icon_width_height = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int widget_min_height = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int widget_min_width = 2131099650;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_disabled = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_disabled_focused = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_focused = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_selector = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int contact_picture_placeholder = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int error = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int list_focused = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int list_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int list_selector = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int list_selector_disabled = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int noise = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int overlay_selector = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int placeholder = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0002
			public const int activity_list = 2131361794;
			
			// aapt resource value: 0x7f0a0004
			public const int animator = 2131361796;
			
			// aapt resource value: 0x7f0a0003
			public const int faux_action_bar_control = 2131361795;
			
			// aapt resource value: 0x7f0a0007
			public const int go = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int grid_view = 2131361800;
			
			// aapt resource value: 0x7f0a0005
			public const int image = 2131361797;
			
			// aapt resource value: 0x7f0a0000
			public const int photo = 2131361792;
			
			// aapt resource value: 0x7f0a0006
			public const int progress = 2131361798;
			
			// aapt resource value: 0x7f0a0001
			public const int sample_content = 2131361793;
			
			// aapt resource value: 0x7f0a0009
			public const int url = 2131361801;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int column_count = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int notification_view = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int picasso_sample_activity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int picasso_sample_activity_item = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int sample_gallery_activity = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int sample_gridview_activity = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int sample_list_detail_detail = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int sample_list_detail_item = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int sample_list_detail_list = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int sample_widget = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080000
			public const int app_name = 2131230720;
			
			// aapt resource value: 0x7f080006
			public const int disk_cache_description = 2131230726;
			
			// aapt resource value: 0x7f080001
			public const int hide = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int more = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int sample_notification = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int sample_widget = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int select_picture = 2131230725;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090008
			public const int Theme_PicassoSample = 2131296264;
			
			// aapt resource value: 0x7f090003
			public const int Widget_PicassoSample_ActionBarButton = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int Widget_PicassoSample_ActionBarTitle = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int Widget_PicassoSample_Button = 2131296256;
			
			// aapt resource value: 0x7f090007
			public const int Widget_PicassoSample_DescriptionText = 2131296263;
			
			// aapt resource value: 0x7f090006
			public const int Widget_PicassoSample_DescriptionUrl = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int Widget_PicassoSample_ListItem = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int Widget_PicassoSample_ListView = 2131296260;
			
			// aapt resource value: 0x7f090001
			public const int Widget_PicassoSample_Overlay = 2131296257;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int sample_widget_info = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
